mail_enabled: true
smtp_server: smtp.example.com
smtp_port: 587
smtp_user: user@example.com
smtp_pass: password
email_from: admin@example.com
email_to: alerts@example.com
smtp_security: starttls
threshold_percent: 10.0
send_mail_on_unknown_status: false
debug: false
health_check_enabled: true
friendly_name: "Example device"
